const loud = 'Annnnnnddd the winner is...'
console.log(loud.replace(/n{3}/, '***')) // A***nnnddd the winner is...
console.log(loud.replace(/n{3,}/, '***')) // A***ddd the winner is...
console.log(loud.replace(/n{3,5}/, '***')) // A***nddd the winner is...
console.log(loud.replace(/h?/, '*')) // *Annnnnnddd the winner is...
console.log(loud.replace(/n+/, '*')) // A*ddd the winner is...
console.log(loud.replace(/An*/, '*')) // *ddd the winner is...